name: Build and Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Building and testing
        uses: ichiro-its/ros2-ci@v1.0.0
        with:
          ros2-distro: foxy
          pre-install: sudo apt update && sudo apt install -y curl && curl -s http://repository.ichiro-its.org/debian/setup.bash | bash -s
          apt-packages: ros-foxy-beine-cpp ros-foxy-gazebo-ros ros-foxy-keisan
